name: Post collaborators JSON
on:
  workflow_dispatch:
  schedule:
    - cron: "23 4 * * *"

jobs:
  post-data-to-opseng-reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: bin/post-data.sh
        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          OPERATIONS_ENGINEERING_REPORTS_API_KEY: ${{ secrets.OPERATIONS_ENGINEERING_REPORTS_API_KEY }}
          OPS_ENG_REPORTS_URL: "https://operations-engineering-reports.cloud-platform.service.justice.gov.uk/github_collaborators"
      - name: Remove manually-added collaborators
        run: bin/remove-undefined-collaborators.rb
        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          OWNER: "ministryofjustice"
          OPS_ENG_REPORTS_URL: "https://operations-engineering-reports.cloud-platform.service.justice.gov.uk/github_collaborators"
